# Qwen 模型配置
model:
  name: Qwen2.5-7B-Instruct
  path: /root/models/Qwen2.5-7B-Instruct
  local: true
  use_cache: true

# 模型信息
info:
  size: 15G
  files: 13

# 训练配置中使用本地路径:
# model:
#   name: /root/models/Qwen2.5-7B-Instruct
