# Minimal Test Configuration
# For quick testing with minimal resources and time

dataset:
  name: AIME24
  data_path: ./data/aime24/data.json
  train_ratio: 0.8
  sample_size: null

# Minimal MCTS parameters
mcts:
  num_iterations: 3              # Very few iterations
  num_samples_per_iteration: 2   # Minimal samples
  num_search_rounds: 2           # Just 2 rounds

# Minimal GRPO parameters
grpo:
  learning_rate: 1.0e-5
  lora_learning_rate: 5.0e-4
  num_epochs: 1                  # Only 1 epoch per training
  batch_size: 2                  # Small batch
  gradient_accumulation_steps: 1
  gamma: 0.99
  lam: 0.95
  entropy_coeff: 0.01
  value_coeff: 0.5
  max_grad_norm: 1.0

model:
  name: /root/models/Qwen2.5-7B-Instruct  # 本地模型路径
  use_lora: true
  lora_rank: 8
  lora_alpha: 16

# Minimal training parameters
training:
  num_epochs: 1                  # Only 1 epoch
  num_episodes: 1                # Only 1 episode
  problems_per_episode: 2        # Only 2 problems
  device: cuda

paths:
  aflow_path: ./AFlow                             # Local AFlow directory
  workspace_path: ./outputs_test
  checkpoint_path: ./checkpoints_test
  log_path: ./logs_test
  drive_path: /content/drive/MyDrive/agentworkflow

checkpoint:
  save_every_n_steps: 100
  save_every_n_epochs: 1

logging:
  level: DEBUG
  save_to_file: true
  log_file: ./logs_test/training.log
